---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../../shared/components/common/repos/app-template
  - ../../../../../shared/components/volsync/aws
  - ../../../../../shared/components/gatus/external
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ingressroute.yaml
