---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-services
  namespace: network
spec:
  targetNamespace: network
  path: ./kubernetes/main/apps/network/traefik/config/external-services
  prune: true
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  wait: false
  interval: 15m
  retryInterval: 1m
  timeout: 2m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-middleware
  namespace: network
spec:
  targetNamespace: network
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
    - name: traefik-external
      namespace: network
  path: ./kubernetes/main/apps/network/traefik/config/middleware
  prune: true
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  wait: false
  interval: 15m
  retryInterval: 1m
  timeout: 2m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-ingress
  namespace: network
spec:
  targetNamespace: network
  dependsOn:
    - name: traefik-middleware
      namespace: network
    - name: external-services
      namespace: network
    - name: certificates
      namespace: cert-manager
  path: ./kubernetes/main/apps/network/traefik/config/ingress-routes
  prune: true
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  wait: false
  interval: 15m
  retryInterval: 1m
  timeout: 2m
