---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${EXTRAVOL}"
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: ["${EXTRAVOL_ACCESSMODES:-ReadWriteOnce}"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "${EXTRAVOL}-dst"
  resources:
    requests:
      storage: "${EXTRAVOL_CAPACITY}"
  storageClassName: "${EXTRAVOL_STORAGECLASS:-ceph-block}"
