---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        # Immich
        HOMEPAGE_VAR_IMMICH_API_KEY: "{{ .IMMICH_API_KEY }}"
        # Home Assistant
        HOMEPAGE_VAR_HOMEASSISTANT_KEY: "{{ .HOME_ASSISTANT_API_KEY }}"
        # https://k8plex.haynesnetwork.com
        HAYNESKUBE_PLEX_API_KEY: "{{ .HAYNESKUBE_PLEX_API_KEY }}"
        # https://plex.haynesnetwork.com
        HAYNESTOWER_PLEX_API_KEY: "{{ .HAYNESTOWER_PLEX_API_KEY }}"
        # Grafana
        GRAFANA_USERNAME: "{{ .GRAFANA_USERNAME }}"
        GRAFANA_PASSWORD: "{{ .GRAFANA_PASSWORD }}"
        # Authentik
        AUTHENTIK_API_TOKEN: "{{ .AUTHENTIK_API_TOKEN }}"
  dataFrom:
    - extract:
        key: homepage
