---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        # Immich
        HOMEPAGE_VAR_IMMICH_API_KEY: "{{ .IMMICH_API_KEY }}"
        # Home Assistant
        HOMEPAGE_VAR_HOMEASSISTANT_KEY: "{{ .HOME_ASSISTANT_API_KEY }}"
        # Paperless-ngx (Homepage widget supports username/password)
        HOMEPAGE_VAR_PAPERLESS_USERNAME: "{{ .ADMIN_USER }}"
        HOMEPAGE_VAR_PAPERLESS_PASSWORD: "{{ .ADMIN_PASS }}"
        # https://k8plex.haynesnetwork.com
        HOMEPAGE_VAR_HAYNESKUBE_PLEX_API_KEY: "{{ .HAYNESKUBE_PLEX_API_KEY }}"
        # https://plex.haynesnetwork.com
        HOMEPAGE_VAR_HAYNESTOWER_PLEX_API_KEY: "{{ .HAYNESTOWER_PLEX_API_KEY }}"
        # Grafana
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_USERNAME }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_PASSWORD }}"
        # Authentik
        HOMEPAGE_VAR_AUTHENTIK_API_TOKEN: "{{ .AUTHENTIK_API_TOKEN }}"
        # Traefik dashboard (basic auth)
        HOMEPAGE_VAR_TRAEFIK_USERNAME: "{{ .TRAEFIK_USERNAME }}"
        HOMEPAGE_VAR_TRAEFIK_PASSWORD: "{{ .TRAEFIK_PASSWORD }}"
  dataFrom:
    - extract:
        key: homepage
    - extract:
        key: paperless
