---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app intel-device-plugin
  namespace: kube-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/apps/kube-system/intel-device-plugin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  wait: false
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: node-feature-discovery
      namespace: kube-system
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app intel-device-plugin-gpu
  namespace: kube-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/apps/kube-system/intel-device-plugin/gpu
  prune: true
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  wait: false
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: intel-device-plugin
      namespace: kube-system
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app intel-device-plugin-exporter
  namespace: kube-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/apps/kube-system/intel-device-plugin/exporter
  prune: true
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  wait: false
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: intel-device-plugin-gpu
      namespace: kube-system
