apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ytdl-sub-peloton
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ytdl-sub-peloton-secret
    template:
      engineVersion: v2
      data:
        PELOTON_BEARER: "{{ .PELOTON_BEARER }}"
  dataFrom:
    - extract:
        key: peloton