apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ytdl-sub-peloton
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ytdl-sub-peloton-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          configuration:
            working_directory: "/workdir/"
        subscriptions-override.yaml: |
          __preset__:
            ytdl_options:
              http_headers:
                Authorization: "{{ .PELOTON_BEARER }}"
                Origin: "https://members.onepeloton.com"
                Referer: "https://members.onepeloton.com/"
  dataFrom:
    - extract:
        key: peloton