---
nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - path: spec/values/persistence/config-template/name
        kind: HelmRelease
      - path: spec/values/persistence/subscriptions/name
        kind: HelmRelease