apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app traefik-external
  namespace: flux-system
spec:
  targetNamespace: &namespace network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cilium
    - name: certificates
      namespace: cert-manager
    - name: reflector
  path: ./kubernetes/main/apps/network/traefik/traefik-external/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: haynes-ops
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 2m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: Deployment
      name: *app
      namespace: *namespace
