---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  chart:
    spec:
      # https://github.com/open-webui/helm-charts/releases
      chart: open-webui
      version: 8.14.0
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: open-webui
  values: # found here https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/values.yaml
    # -- Automatically install Ollama Helm chart from https://otwld.github.io/ollama-helm/. Use [Helm Values](https://github.com/otwld/ollama-helm/#helm-values) to configure
    ollama:
      enabled: false

    # -- A list of Ollama API endpoints. These can be added in lieu of automatically installing the Ollama Helm chart, or in addition to it.
    ollamaUrls: [http://ollama-prime.ai.svc.cluster.local:11434]

    annotations:
      reloader.stakater.com/auto: "true"

    ingress:
      enabled: true
      class: traefik-external
      annotations:
        external-dns.alpha.kubernetes.io/target: haynesnetwork.com
      host: ai.haynesnetwork.com
      tls: true
      existingSecret: certificate-haynesnetwork

    persistence:
      enabled: true
      existingClaim: open-webui

    extraEnvVars:
      GLOBAL_LOG_LEVEL:
        value: "DEBUG"
      OPENAI_API_BASE_URLS:
        value: "http://open-webui-pipelines.ai.svc.cluster.local:9099;https://api.openai.com/v1"
      OPENAI_API_KEYS:
        valueFrom:
          secretKeyRef:
            name: openwebui-secret
            key: OPENAI_API_KEYS
      OPENID_PROVIDER_URL:
        value: "https://authentik.haynesnetwork.com/application/o/open-webui/.well-known/openid-configuration"
      OAUTH_CLIENT_ID:
        valueFrom:
          secretKeyRef:
            name: openwebui-secret
            key: OAUTH_CLIENT_ID
      OAUTH_CLIENT_SECRET:
        valueFrom:
          secretKeyRef:
            name: openwebui-secret
            key: OAUTH_CLIENT_SECRET
      OAUTH_PROVIDER_NAME:
        value: "authentik"
      ENABLE_OAUTH_SIGNUP:
        value: "true"
      ENABLE_LOGIN_FORM:
        value: "false"
      DEFAULT_USER_ROLE:
        value: "user"