---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8tz
  namespace: k8tz
spec:
  targetNamespace: k8tz
  commonMetadata:
    labels:
      app.kubernetes.io/name: k8tz
  dependsOn:
    - name: certificates
      namespace: cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  path: ./kubernetes/main/apps/kube-system/k8tz/app
  wait: true
  interval: 30m
  timeout: 5m
