__preset__:
  overrides:
    tv_show_directory: /media/peloton
    only_recent_date_range: 24months
    only_recent_max_files: 300
  output_options:
    output_directory: '{tv_show_directory}'
    file_name: S{season_number}E{episode_number} - {upload_date} - {title}/S{season_number}E{episode_number} - {upload_date} - {title}.{ext}
    thumbnail_name: S{season_number}E{episode_number} - {upload_date} - {title}/S{season_number}E{episode_number} - {upload_date} - {title}-thumb.jpg
    info_json_name: S{season_number}E{episode_number} - {upload_date} - {title}/S{season_number}E{episode_number} - {upload_date} - {title}.info.json
  throttle_protection:
    sleep_per_download_s:
      min: 120
      max: 270
    sleep_per_subscription_s:
      min: 60
      max: 90
    max_downloads_per_subscription:
      min: 25
      max: 75
    subscription_download_probability: 1
  ytdl_options:
    usenetrc: true
    format: bestvideo+bestaudio/bestaudio
    merge_output_format: mp4
Plex TV Show by Date:
  = Walking (20 min):
    20 min Pop Walk with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/fe30657f7b164c37ae56f0e0aa3324a9
      overrides:
        tv_show_directory: /media/peloton/Walking/Hannah Frankson
        season_number: 20
        episode_number: 38
    20 min 80s Walk with Susie Chan:
      download: https://members.onepeloton.com/classes/player/e8524c0cd1d04aacaab74f3e53dbf7e7
      overrides:
        tv_show_directory: /media/peloton/Walking/Susie Chan
        season_number: 20
        episode_number: 58
  = Cycling (30 min):
    30 min Pop Ride with Jenn Sherman:
      download: https://members.onepeloton.com/classes/player/333d40d6a1e34961af6343d8a2ba9a63
      overrides:
        tv_show_directory: /media/peloton/Cycling/Jenn Sherman
        season_number: 30
        episode_number: 151
    30 min Feel Good Ride with Ally Love:
      download: https://members.onepeloton.com/classes/player/9dcd3e8a595f4c1892bd3f96e63d0d6e
      overrides:
        tv_show_directory: /media/peloton/Cycling/Ally Love
        season_number: 30
        episode_number: 152
    30 min Classic Rock Ride with Ben Alldis:
      download: https://members.onepeloton.com/classes/player/1c7e1fbb07594259a00d9e7323113107
      overrides:
        tv_show_directory: /media/peloton/Cycling/Ben Alldis
        season_number: 30
        episode_number: 153
    30 min 90s Rock Ride with Emma Lovewell:
      download: https://members.onepeloton.com/classes/player/d94896fde49d431c9a82fd7788441b40
      overrides:
        tv_show_directory: /media/peloton/Cycling/Emma Lovewell
        season_number: 30
        episode_number: 154
    30 min Low Impact Ride with Leanne Hainsby-Alldis:
      download: https://members.onepeloton.com/classes/player/458de7b8e1ba4de0aa2c1ffe7a164748
      overrides:
        tv_show_directory: /media/peloton/Cycling/Leanne Hainsby-Alldis
        season_number: 30
        episode_number: 155
    30 min EDM Ride with Olivia Amato:
      download: https://members.onepeloton.com/classes/player/55cd22773fee472ebfff265c90322cf4
      overrides:
        tv_show_directory: /media/peloton/Cycling/Olivia Amato
        season_number: 30
        episode_number: 156
    30 min Metal Ride with Charlotte Weidenbach:
      download: https://members.onepeloton.com/classes/player/dbbab4f38a034cda8bb4a068601136ba
      overrides:
        tv_show_directory: /media/peloton/Cycling/Charlotte Weidenbach
        season_number: 30
        episode_number: 157
    30 min 2010s Hip Hop Ride with Ally Love:
      download: https://members.onepeloton.com/classes/player/a6628c0f9df941b6ae0862a7c1ad9c40
      overrides:
        tv_show_directory: /media/peloton/Cycling/Ally Love
        season_number: 30
        episode_number: 158
    30 min Intervals & Arms Ride with Leanne Hainsby-Alldis:
      download: https://members.onepeloton.com/classes/player/4e4e865888964956842f94c1e5b6f1e6
      overrides:
        tv_show_directory: /media/peloton/Cycling/Leanne Hainsby-Alldis
        season_number: 30
        episode_number: 159
  = Cycling (10 min):
    'Extra 10: Tabata Ride with Olivia Amato':
      download: https://members.onepeloton.com/classes/player/5fb5bd16a4d1497ca5e19564255dad58
      overrides:
        tv_show_directory: /media/peloton/Cycling/Olivia Amato
        season_number: 10
        episode_number: 10
    10 min Warm Up Ride with Ben Alldis:
      download: https://members.onepeloton.com/classes/player/224f5bba319f4f528ee8d08851594139
      overrides:
        tv_show_directory: /media/peloton/Cycling/Ben Alldis
        season_number: 10
        episode_number: 11
  = Cycling (20 min):
    20 min Beginner Ride with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/3999509920d647869916871a7787dd28
      overrides:
        tv_show_directory: /media/peloton/Cycling/Hannah Frankson
        season_number: 20
        episode_number: 74
    20 min HIIT Ride with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/856dd27b0a0f4007a37442b826de341d
      overrides:
        tv_show_directory: /media/peloton/Cycling/Hannah Frankson
        season_number: 20
        episode_number: 75
    20 min Pop Ride with Sam Yo:
      download: https://members.onepeloton.com/classes/player/6613fdfda4a5452492b3f5f94831bfdb
      overrides:
        tv_show_directory: /media/peloton/Cycling/Sam Yo
        season_number: 20
        episode_number: 76
    20 min Rolling Hills Ride with Emma Lovewell:
      download: https://members.onepeloton.com/classes/player/c8ac5eb9e15845d4add7d640e7f61eb5
      overrides:
        tv_show_directory: /media/peloton/Cycling/Emma Lovewell
        season_number: 20
        episode_number: 77
    20 min 80s Ride with Emma Lovewell:
      download: https://members.onepeloton.com/classes/player/5453ff4a0d99413ca42de68ea94703b6
      overrides:
        tv_show_directory: /media/peloton/Cycling/Emma Lovewell
        season_number: 20
        episode_number: 78
  = Cycling (15 min):
    15 min Low Impact Ride with Camila Ramón:
      download: https://members.onepeloton.com/classes/player/785338e49e94404c8a5554e0a577dc72
      overrides:
        tv_show_directory: /media/peloton/Cycling/Camila Ramón
        season_number: 15
        episode_number: 23
    15 min Hip Hop Ride with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/bf635326a75943f7bc1191decddc7bab
      overrides:
        tv_show_directory: /media/peloton/Cycling/Hannah Frankson
        season_number: 15
        episode_number: 24
    15 min Low Impact Ride with Sam Yo:
      download: https://members.onepeloton.com/classes/player/d35ab50997ae401f8facc0c9d695a9bd
      overrides:
        tv_show_directory: /media/peloton/Cycling/Sam Yo
        season_number: 15
        episode_number: 25
  = Cycling (60 min):
    60 min 80s Ride with Jenn Sherman:
      download: https://members.onepeloton.com/classes/player/0d0ee197a69c4cac8c2e9e9b49857c68
      overrides:
        tv_show_directory: /media/peloton/Cycling/Jenn Sherman
        season_number: 60
        episode_number: 5
    60 min Sweat Steady Ride with Jess King:
      download: https://members.onepeloton.com/classes/player/d1068b57b3534dc6a1bb8a5eb2e28706
      overrides:
        tv_show_directory: /media/peloton/Cycling/Jess King
        season_number: 60
        episode_number: 6
  = Cycling (90 min):
    90 min Power Zone Endurance Ride with Denis & Matt:
      download: https://members.onepeloton.com/classes/player/aab6d338d6e04d6780873bdabafc1d45
      overrides:
        tv_show_directory: /media/peloton/Cycling/Denis & Matt
        season_number: 90
        episode_number: 1
  = Running (10 min):
    'Extra 10: Endurance with Hannah Frankson':
      download: https://members.onepeloton.com/classes/player/6aa9343e1ab04656abacda288058db55
      overrides:
        tv_show_directory: /media/peloton/Running/Hannah Frankson
        season_number: 10
        episode_number: 9
  = Running (45 min):
    45 min Endurance Run with Marcel Dinkins:
      download: https://members.onepeloton.com/classes/player/9651ebc6c28f4c738bcacc63a563f9b3
      overrides:
        tv_show_directory: /media/peloton/Running/Marcel Dinkins
        season_number: 45
        episode_number: 19
    45 min 80s Run with Marcel Dinkins:
      download: https://members.onepeloton.com/classes/player/e1a0c6799b2441fabe21448844cad99f
      overrides:
        tv_show_directory: /media/peloton/Running/Marcel Dinkins
        season_number: 45
        episode_number: 20
  = Running (30 min):
    30 min Trap Run with Kirsten Ferguson:
      download: https://members.onepeloton.com/classes/player/0d17035dd4d34692b83468e5a0d7a5df
      overrides:
        tv_show_directory: /media/peloton/Running/Kirsten Ferguson
        season_number: 30
        episode_number: 114
    30 min 80s Run with Joslyn Thompson Rule:
      download: https://members.onepeloton.com/classes/player/99fc4b66d2054e24bf5d9b3ced120d67
      overrides:
        tv_show_directory: /media/peloton/Running/Joslyn Thompson Rule
        season_number: 30
        episode_number: 115
    30 min Rising Pop Run with Robin Arzón:
      download: https://members.onepeloton.com/classes/player/d903481572a04b80b0b080f28194c22b
      overrides:
        tv_show_directory: /media/peloton/Running/Robin Arzón
        season_number: 30
        episode_number: 116
    30 min Intervals Run with Alex Karwoski:
      download: https://members.onepeloton.com/classes/player/f7177d1303694ecf9d6dee01255b0e07
      overrides:
        tv_show_directory: /media/peloton/Running/Alex Karwoski
        season_number: 30
        episode_number: 117
    30 min 2010s Run with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/1c609958a1364751ae2862d9d565f623
      overrides:
        tv_show_directory: /media/peloton/Running/Hannah Frankson
        season_number: 30
        episode_number: 118
    30 min House Run with Olivia Amato:
      download: https://members.onepeloton.com/classes/player/ee1b2691abb346efb1b5e053bc39ca0e
      overrides:
        tv_show_directory: /media/peloton/Running/Olivia Amato
        season_number: 30
        episode_number: 119
    30 min Endurance Run with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/9c0234aa44264df8b6585e495f671de1
      overrides:
        tv_show_directory: /media/peloton/Running/Hannah Frankson
        season_number: 30
        episode_number: 120
  = Running (20 min):
    20 min 2000s Run with Jon Hosking:
      download: https://members.onepeloton.com/classes/player/625421dd04ec42d09527f61d28d387c7
      overrides:
        tv_show_directory: /media/peloton/Running/Jon Hosking
        season_number: 20
        episode_number: 68
    20 min 2000s Run with Susie Chan:
      download: https://members.onepeloton.com/classes/player/3fc05c57916d4f5a8edb64999111eaf5
      overrides:
        tv_show_directory: /media/peloton/Running/Susie Chan
        season_number: 20
        episode_number: 69
  = Walking (30 min):
    30 min Hike with Kirsten Ferguson:
      download: https://members.onepeloton.com/classes/player/79c4c8d15564473892fa801f51b76e66
      overrides:
        tv_show_directory: /media/peloton/Walking/Kirsten Ferguson
        season_number: 30
        episode_number: 97
    30 min Hike with Joslyn Thompson Rule:
      download: https://members.onepeloton.com/classes/player/cda681c716c34a02a92202f5d138fdfa
      overrides:
        tv_show_directory: /media/peloton/Walking/Joslyn Thompson Rule
        season_number: 30
        episode_number: 98
    30 min Pride Pop Walk with Matty Maggiacomo:
      download: https://members.onepeloton.com/classes/player/7a22ba645d4d4962886ecd906dc0356e
      overrides:
        tv_show_directory: /media/peloton/Walking/Matty Maggiacomo
        season_number: 30
        episode_number: 99
    30 min 90s Walk with Joslyn Thompson Rule:
      download: https://members.onepeloton.com/classes/player/72f126a102d445f98f3af0ce1851351a
      overrides:
        tv_show_directory: /media/peloton/Walking/Joslyn Thompson Rule
        season_number: 30
        episode_number: 100
    30 min Walk + Run with Camila Ramón:
      download: https://members.onepeloton.com/classes/player/c70ac0942e134731954cccf3208721ff
      overrides:
        tv_show_directory: /media/peloton/Walking/Camila Ramón
        season_number: 30
        episode_number: 101
  = Walking (10 min):
    'Extra 10: Hike with Jon Hosking':
      download: https://members.onepeloton.com/classes/player/5e40aaf249514b079141b7cba5aea516
      overrides:
        tv_show_directory: /media/peloton/Walking/Jon Hosking
        season_number: 10
        episode_number: 15
    10 min Cool Down Walk with Susie Chan:
      download: https://members.onepeloton.com/classes/player/57e45590c99549838fc2493dead1d5b9
      overrides:
        tv_show_directory: /media/peloton/Walking/Susie Chan
        season_number: 10
        episode_number: 16
  = Walking (45 min):
    45 min On the Dancefloor Walk with Jess King:
      download: https://members.onepeloton.com/classes/player/e03693ed5030430a99a521d8a0dd9d9c
      overrides:
        tv_show_directory: /media/peloton/Walking/Jess King
        season_number: 45
        episode_number: 17
  = Tread Bootcamp (60 min):
    Sims 60 with Jess Sims:
      download: https://members.onepeloton.com/classes/player/b9b0519fc671474d889d2b8382f6b490
      overrides:
        tv_show_directory: /media/peloton/Tread Bootcamp/Jess Sims
        season_number: 60
        episode_number: 31
  = Tread Bootcamp (45 min):
    Thunder 45 with Adrian Williams:
      download: https://members.onepeloton.com/classes/player/e5367c3471724c5da4e6561be5dd090f
      overrides:
        tv_show_directory: /media/peloton/Tread Bootcamp/Adrian Williams
        season_number: 45
        episode_number: 100
  = Rowing (30 min):
    30 min Rock Row with Katie Wang:
      download: https://members.onepeloton.com/classes/player/11e2648136f54588a1c5f0292ae13ec4
      overrides:
        tv_show_directory: /media/peloton/Rowing/Katie Wang
        season_number: 30
        episode_number: 45
    30 min Endurance Row with Alex Karwoski:
      download: https://members.onepeloton.com/classes/player/5787c57296f3452a8951aa0a72a7e76b
      overrides:
        tv_show_directory: /media/peloton/Rowing/Alex Karwoski
        season_number: 30
        episode_number: 46
  = Strength (20 min):
    20 min Chest & Back Strength with Logan Aldridge:
      download: https://members.onepeloton.com/classes/player/d93cfdcd3d0f45a6a2c6624f6666fb5a
      overrides:
        tv_show_directory: /media/peloton/Strength/Logan Aldridge
        season_number: 20
        episode_number: 86
    20 min Arms & Shoulders Strength with Olivia Amato:
      download: https://members.onepeloton.com/classes/player/3cded7c5804c4115b76a1a30dcc26462
      overrides:
        tv_show_directory: /media/peloton/Strength/Olivia Amato
        season_number: 20
        episode_number: 87
  = Strength (15 min):
    15 min Core Strength with Logan Aldridge:
      download: https://members.onepeloton.com/classes/player/69822d1c5e0a4c7ca21befe0f0deaf5a
      overrides:
        tv_show_directory: /media/peloton/Strength/Logan Aldridge
        season_number: 15
        episode_number: 21
  = Strength (30 min):
    30 min Full Body Strength with Jess Sims:
      download: https://members.onepeloton.com/classes/player/dc76db197e4a4fd986c42c322bb72811
      overrides:
        tv_show_directory: /media/peloton/Strength/Jess Sims
        season_number: 30
        episode_number: 49
    30 min Disney Upper Body Strength with Callie Gullickson:
      download: https://members.onepeloton.com/classes/player/38e7e07a10c14e74986c8a7ba1ef6e7e
      overrides:
        tv_show_directory: /media/peloton/Strength/Callie Gullickson
        season_number: 30
        episode_number: 50
    30 min Full Body Strength with Ben Alldis:
      download: https://members.onepeloton.com/classes/player/59d34aff2be14dcc9404ecdcd825e534
      overrides:
        tv_show_directory: /media/peloton/Strength/Ben Alldis
        season_number: 30
        episode_number: 51
  = Strength (10 min):
    10 min Core Strength with Olivia Amato:
      download: https://members.onepeloton.com/classes/player/6a63ca6eb8e94f6c9325af4b063f8325
      overrides:
        tv_show_directory: /media/peloton/Strength/Olivia Amato
        season_number: 10
        episode_number: 64
  = Yoga (30 min):
    30 min Restorative with Kirra Michel:
      download: https://members.onepeloton.com/classes/player/9abf555fcad3491cb2dfaf2d6d6d9fce
      overrides:
        tv_show_directory: /media/peloton/Yoga/Kirra Michel
        season_number: 30
        episode_number: 117
    30 min Yin Yoga with Chelsea Jackson Roberts:
      download: https://members.onepeloton.com/classes/player/5a62ee40f9ce496dbb1e30ef9a091e65
      overrides:
        tv_show_directory: /media/peloton/Yoga/Chelsea Jackson Roberts
        season_number: 30
        episode_number: 118
  = Cycling (45 min):
    45 min Rock Ride with Jenn Sherman:
      download: https://members.onepeloton.com/classes/player/be032b672e60496b8952ffa0d676e247
      overrides:
        tv_show_directory: /media/peloton/Cycling/Jenn Sherman
        season_number: 45
        episode_number: 48
    '45 min Pro Cyclist: HIIT Training Ride with Christian Vande Velde':
      download: https://members.onepeloton.com/classes/player/1fc40de2914c428494e9c528219e8fee
      overrides:
        tv_show_directory: /media/peloton/Cycling/Christian Vande Velde
        season_number: 45
        episode_number: 49
  = Rowing (15 min):
    15 min Beginner Row with Alex Karwoski:
      download: https://members.onepeloton.com/classes/player/9ceeb800ecbb45f3a0467da5f7b9950c
      overrides:
        tv_show_directory: /media/peloton/Rowing/Alex Karwoski
        season_number: 15
        episode_number: 40
  = Rowing (20 min):
    20 min Endurance Row with Ash Pryor:
      download: https://members.onepeloton.com/classes/player/c8a675a7a17c415db13089d47dd3e5f7
      overrides:
        tv_show_directory: /media/peloton/Rowing/Ash Pryor
        season_number: 20
        episode_number: 75
