__preset__:
  overrides:
    tv_show_directory: /media/peloton
    only_recent_date_range: 24months
    only_recent_max_files: 300
  output_options:
    output_directory: '{tv_show_directory}'
    file_name: S{season_number}E{episode_number} - {upload_date} - {title}/S{season_number}E{episode_number} - {upload_date} - {title}.{ext}
    thumbnail_name: S{season_number}E{episode_number} - {upload_date} - {title}/S{season_number}E{episode_number} - {upload_date} - {title}-thumb.jpg
    info_json_name: S{season_number}E{episode_number} - {upload_date} - {title}/S{season_number}E{episode_number} - {upload_date} - {title}.info.json
  throttle_protection:
    sleep_per_download_s:
      min: 120
      max: 270
    sleep_per_subscription_s:
      min: 60
      max: 90
    max_downloads_per_subscription:
      min: 25
      max: 75
    subscription_download_probability: 1
  ytdl_options:
    usenetrc: true
    format: bestvideo+bestaudio/bestaudio
    merge_output_format: mp4
Plex TV Show by Date:
  = Walking (20 min):
    20 min Pop Walk with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/fe30657f7b164c37ae56f0e0aa3324a9
      overrides:
        tv_show_directory: /media/peloton/Walking/Hannah Frankson
        season_number: 20
        episode_number: 38
  = Strength (10 min):
    10 min Luther Vandross Arms with Sam Yo:
      download: https://members.onepeloton.com/classes/player/86b7efb5306045c69f3584ed4852e950
      overrides:
        tv_show_directory: /media/peloton/Strength/Sam Yo
        season_number: 10
        episode_number: 74
    10 min Arms & Light Weights with Camila Ramón:
      download: https://members.onepeloton.com/classes/player/16ad8a80e39f400ebf8d0f90e87167ea
      overrides:
        tv_show_directory: /media/peloton/Strength/Camila Ramón
        season_number: 10
        episode_number: 75
    10 min Arms & Light Weights with Marcel Dinkins:
      download: https://members.onepeloton.com/classes/player/d108d14ffda345df88df4ff544b0398e
      overrides:
        tv_show_directory: /media/peloton/Strength/Marcel Dinkins
        season_number: 10
        episode_number: 76
    10 min Core Strength with Rebecca Kennedy:
      download: https://members.onepeloton.com/classes/player/969274c2cd514568a70de99c1208d9e1
      overrides:
        tv_show_directory: /media/peloton/Strength/Rebecca Kennedy
        season_number: 10
        episode_number: 77
  = Strength (5 min):
    5 min Upper Body Strength Warm Up with Katie Wang:
      download: https://members.onepeloton.com/classes/player/5cd602531dce4d4db63da135ce7a88c1
      overrides:
        tv_show_directory: /media/peloton/Strength/Katie Wang
        season_number: 5
        episode_number: 15
  = Strength (20 min):
    20 min Full Body Strength with Robin Arzón:
      download: https://members.onepeloton.com/classes/player/3f742075ddce4ed7ad4d8c4c9dd33a94
      overrides:
        tv_show_directory: /media/peloton/Strength/Robin Arzón
        season_number: 20
        episode_number: 95
    20 min Bollywood Pilates with Aditi Shah:
      download: https://members.onepeloton.com/classes/player/1e7e4690d37b4aa8adf909c3285e4a06
      overrides:
        tv_show_directory: /media/peloton/Strength/Aditi Shah
        season_number: 20
        episode_number: 96
    20 min Upper Body Strength with Katie Wang:
      download: https://members.onepeloton.com/classes/player/0df1dea87c7947a1b53e01a83470c65d
      overrides:
        tv_show_directory: /media/peloton/Strength/Katie Wang
        season_number: 20
        episode_number: 97
    20 min Kettlebell Strength&Conditioning with Logan Aldridge:
      download: https://members.onepeloton.com/classes/player/05b8818d5d1442c7934a217626831771
      overrides:
        tv_show_directory: /media/peloton/Strength/Logan Aldridge
        season_number: 20
        episode_number: 98
    20 min Chest & Back Strength with Adrian Williams:
      download: https://members.onepeloton.com/classes/player/67f976f92fc9438abe759301ebd814f1
      overrides:
        tv_show_directory: /media/peloton/Strength/Adrian Williams
        season_number: 20
        episode_number: 99
    20 min Glutes & Legs Strength with Joslyn Thompson Rule:
      download: https://members.onepeloton.com/classes/player/b76b821bb03b4b888f92343386f41e5e
      overrides:
        tv_show_directory: /media/peloton/Strength/Joslyn Thompson Rule
        season_number: 20
        episode_number: 100
    20 min Full Body Strength with Matty Maggiacomo:
      download: https://members.onepeloton.com/classes/player/5a9b9692e3cb4f32af4e75a72576225a
      overrides:
        tv_show_directory: /media/peloton/Strength/Matty Maggiacomo
        season_number: 20
        episode_number: 101
  = Strength (15 min):
    15 min Core Strength with Emma Lovewell:
      download: https://members.onepeloton.com/classes/player/1a89b7c3d0774620b69193e4ad5973ec
      overrides:
        tv_show_directory: /media/peloton/Strength/Emma Lovewell
        season_number: 15
        episode_number: 27
  = Yoga (30 min):
    30 min Luther Vandross Yoga Flow with Chelsea Jackson Roberts:
      download: https://members.onepeloton.com/classes/player/689b85d7d9484bd488fba8f1822429d5
      overrides:
        tv_show_directory: /media/peloton/Yoga/Chelsea Jackson Roberts
        season_number: 30
        episode_number: 125
  = Yoga (10 min):
    '10 min Focus Flow: Wrists with Chelsea Jackson Roberts':
      download: https://members.onepeloton.com/classes/player/fb6ee681719e4dbf9068cd6b09b50e6a
      overrides:
        tv_show_directory: /media/peloton/Yoga/Chelsea Jackson Roberts
        season_number: 10
        episode_number: 20
    10 min Restorative with Denis Morton:
      download: https://members.onepeloton.com/classes/player/5e8b1466b39a4519bcb15bcf03647aae
      overrides:
        tv_show_directory: /media/peloton/Yoga/Denis Morton
        season_number: 10
        episode_number: 21
  = Yoga (15 min):
    '15 min Focus Flow: Core with Kirra Michel':
      download: https://members.onepeloton.com/classes/player/1ffe876be028417bb960287340b19b70
      overrides:
        tv_show_directory: /media/peloton/Yoga/Kirra Michel
        season_number: 15
        episode_number: 20
  = Yoga (20 min):
    20 min Yoga Flow with Kirra Michel:
      download: https://members.onepeloton.com/classes/player/7b7a180bea5c478cac276f0a3d1b3273
      overrides:
        tv_show_directory: /media/peloton/Yoga/Kirra Michel
        season_number: 20
        episode_number: 68
    20 min Morning Power Flow with Nico Sarani:
      download: https://members.onepeloton.com/classes/player/313b4a9201124b9ba199c730d1167c80
      overrides:
        tv_show_directory: /media/peloton/Yoga/Nico Sarani
        season_number: 20
        episode_number: 69
  = Meditation (15 min):
    15 min Breathing Walking Meditation with Anna Greenberg:
      download: https://members.onepeloton.com/classes/player/4e2551ed97a2472fb65e8bf71cca1047
      overrides:
        tv_show_directory: /media/peloton/Meditation/Anna Greenberg
        season_number: 15
        episode_number: 22
  = Meditation (10 min):
    10 min Morning Meditation with Nico Sarani:
      download: https://members.onepeloton.com/classes/player/3ce16cb026734f3f85d55eca8defd1f7
      overrides:
        tv_show_directory: /media/peloton/Meditation/Nico Sarani
        season_number: 10
        episode_number: 213
  = Cardio (20 min):
    20 min Low Impact Cardio with Rebecca Kennedy:
      download: https://members.onepeloton.com/classes/player/120f130c5eac40988747187f48b3ff1c
      overrides:
        tv_show_directory: /media/peloton/Cardio/Rebecca Kennedy
        season_number: 20
        episode_number: 119
  = Stretching (5 min):
    5 min Post-Run Stretch with Matt Wilpers:
      download: https://members.onepeloton.com/classes/player/1331d791cadb4faba4c86065b483dcc1
      overrides:
        tv_show_directory: /media/peloton/Stretching/Matt Wilpers
        season_number: 5
        episode_number: 138
  = Stretching (10 min):
    10 min Lower Body Stretch with Logan Aldridge:
      download: https://members.onepeloton.com/classes/player/196646e4e997463f9acaf76a2be24b92
      overrides:
        tv_show_directory: /media/peloton/Stretching/Logan Aldridge
        season_number: 10
        episode_number: 78
  = Cycling (30 min):
    30 min Luther Vandross Ride with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/53c2e8ad60e246d68a6dd148832b48c0
      overrides:
        tv_show_directory: /media/peloton/Cycling/Hannah Frankson
        season_number: 30
        episode_number: 180
    30 min The Cookout Two for One Ride with Alex & Tunde:
      download: https://members.onepeloton.com/classes/player/2ab10fa0624b48f39ca028d187b4132c
      overrides:
        tv_show_directory: /media/peloton/Cycling/Alex & Tunde
        season_number: 30
        episode_number: 181
    30 min Low Impact Ride with Cody Rigsby:
      download: https://members.onepeloton.com/classes/player/d4e203fbb7f54bf09e8f791930c20af4
      overrides:
        tv_show_directory: /media/peloton/Cycling/Cody Rigsby
        season_number: 30
        episode_number: 182
    30 min Pop Punk Ride with Emma Lovewell:
      download: https://members.onepeloton.com/classes/player/374bc301a5f644868ef511cf4706fe75
      overrides:
        tv_show_directory: /media/peloton/Cycling/Emma Lovewell
        season_number: 30
        episode_number: 183
  = Cycling (5 min):
    5 min Cool Down Ride with Jess King:
      download: https://members.onepeloton.com/classes/player/9be2e088ddb7437ebf4c647f8beb32c7
      overrides:
        tv_show_directory: /media/peloton/Cycling/Jess King
        season_number: 5
        episode_number: 14
  = Cycling (20 min):
    20 min Recovery Ride with Jess King:
      download: https://members.onepeloton.com/classes/player/941b84ea2bee470e95a8272df526bbc2
      overrides:
        tv_show_directory: /media/peloton/Cycling/Jess King
        season_number: 20
        episode_number: 90
    20 min Rolling Hills Ride with Jess King:
      download: https://members.onepeloton.com/classes/player/89cc4dd7fec34708a5f1c90f6054ef95
      overrides:
        tv_show_directory: /media/peloton/Cycling/Jess King
        season_number: 20
        episode_number: 91
    20 min 2010s Ride with Bradley Rose:
      download: https://members.onepeloton.com/classes/player/de6cae6617884fc3aaebc42c41806b0e
      overrides:
        tv_show_directory: /media/peloton/Cycling/Bradley Rose
        season_number: 20
        episode_number: 92
    20 min 80s Pop Ride with Ally Love:
      download: https://members.onepeloton.com/classes/player/259d70f9a6394761be311f02c904b129
      overrides:
        tv_show_directory: /media/peloton/Cycling/Ally Love
        season_number: 20
        episode_number: 93
    20 min Tropical House Ride with Ally Love:
      download: https://members.onepeloton.com/classes/player/187947b543774d35ba38443fcdb6dc57
      overrides:
        tv_show_directory: /media/peloton/Cycling/Ally Love
        season_number: 20
        episode_number: 94
  = Cycling (45 min):
    45 min Progressive Push with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/1d1bf9a3341149218dd9d89250567ed7
      overrides:
        tv_show_directory: /media/peloton/Cycling/Hannah Frankson
        season_number: 45
        episode_number: 63
    45 min 80s Ride with Sam Yo:
      download: https://members.onepeloton.com/classes/player/37f8db6f49d846f88074371e31e7c655
      overrides:
        tv_show_directory: /media/peloton/Cycling/Sam Yo
        season_number: 45
        episode_number: 64
  = Cycling (15 min):
    15 min HIIT Ride with Bradley Rose:
      download: https://members.onepeloton.com/classes/player/831fc0c5decc4ab19d161c8f7d9dcbe7
      overrides:
        tv_show_directory: /media/peloton/Cycling/Bradley Rose
        season_number: 15
        episode_number: 28
  = Running (30 min):
    30 min Luther Vandross Run with Jess Sims:
      download: https://members.onepeloton.com/classes/player/479a68b9e7e640d4b59462d72aad5d21
      overrides:
        tv_show_directory: /media/peloton/Running/Jess Sims
        season_number: 30
        episode_number: 135
    30 min Advanced Beginner Run with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/dad1193452eb49abb93f235f84b87c69
      overrides:
        tv_show_directory: /media/peloton/Running/Hannah Frankson
        season_number: 30
        episode_number: 136
    30 min Intervals Run with Selena Samuela:
      download: https://members.onepeloton.com/classes/player/959ff1961e444f17b738ab5aba8e636c
      overrides:
        tv_show_directory: /media/peloton/Running/Selena Samuela
        season_number: 30
        episode_number: 137
    30 min Intervals Run with Alex Karwoski:
      download: https://members.onepeloton.com/classes/player/0d4a994d09f74faa82952c324616f0c1
      overrides:
        tv_show_directory: /media/peloton/Running/Alex Karwoski
        season_number: 30
        episode_number: 138
    30 min Classic Rock Run with Jon Hosking:
      download: https://members.onepeloton.com/classes/player/7c9c7157ab4f41208bdbbf0203e75f67
      overrides:
        tv_show_directory: /media/peloton/Running/Jon Hosking
        season_number: 30
        episode_number: 139
    30 min Endurance Run with Matt Wilpers:
      download: https://members.onepeloton.com/classes/player/734de2b09d8c470eb1e3974e135501fe
      overrides:
        tv_show_directory: /media/peloton/Running/Matt Wilpers
        season_number: 30
        episode_number: 140
  = Running (20 min):
    20 min HIIT Run with Robin Arzón:
      download: https://members.onepeloton.com/classes/player/2ef703a26df548218fb13755ab08b388
      overrides:
        tv_show_directory: /media/peloton/Running/Robin Arzón
        season_number: 20
        episode_number: 76
    20 min 90s Run with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/12f2e589d5de46d58bd96cf0e34e1c11
      overrides:
        tv_show_directory: /media/peloton/Running/Hannah Frankson
        season_number: 20
        episode_number: 77
  = Running (15 min):
    15 min 2000s Run with Joslyn Thompson Rule:
      download: https://members.onepeloton.com/classes/player/d2295e71964c4917a4db254b9e7d1946
      overrides:
        tv_show_directory: /media/peloton/Running/Joslyn Thompson Rule
        season_number: 15
        episode_number: 20
  = Running (45 min):
    45 min Pop Run with Susie Chan:
      download: https://members.onepeloton.com/classes/player/d964d79edf9b4932991bd188c7c4b27f
      overrides:
        tv_show_directory: /media/peloton/Running/Susie Chan
        season_number: 45
        episode_number: 21
  = Walking (30 min):
    30 min Juneteenth Walk with Marcel Dinkins:
      download: https://members.onepeloton.com/classes/player/5c63255474f34617b6011d358515ab11
      overrides:
        tv_show_directory: /media/peloton/Walking/Marcel Dinkins
        season_number: 30
        episode_number: 114
  = Walking (15 min):
    15 min Walk + Run with Kirsten Ferguson:
      download: https://members.onepeloton.com/classes/player/584d34e7f2464943a737906ae926c956
      overrides:
        tv_show_directory: /media/peloton/Walking/Kirsten Ferguson
        season_number: 15
        episode_number: 25
    15 min Power Walk with Joslyn Thompson Rule:
      download: https://members.onepeloton.com/classes/player/2ff58a51b310440b87a4827f0ccedf72
      overrides:
        tv_show_directory: /media/peloton/Walking/Joslyn Thompson Rule
        season_number: 15
        episode_number: 26
  = Walking (45 min):
    45 min Power Walk with Selena Samuela:
      download: https://members.onepeloton.com/classes/player/910e05c26fe94ada9a5daaf7e65830fc
      overrides:
        tv_show_directory: /media/peloton/Walking/Selena Samuela
        season_number: 45
        episode_number: 19
  = Tread Bootcamp (30 min):
    30 min Walking Bootcamp with Kirsten Ferguson:
      download: https://members.onepeloton.com/classes/player/a08739618eac4335a69b527f96e7d261
      overrides:
        tv_show_directory: /media/peloton/Tread Bootcamp/Kirsten Ferguson
        season_number: 30
        episode_number: 104
  = Bike Bootcamp (45 min):
    '45 min Bootcamp: 50-50 with Tunde Oyeneyin':
      download: https://members.onepeloton.com/classes/player/56a10851bdd24ffd9900b8f3fc1c257e
      overrides:
        tv_show_directory: /media/peloton/Bike Bootcamp/Tunde Oyeneyin
        season_number: 45
        episode_number: 67
  = Rowing (20 min):
    20 min Luther Vandross Row with Becs Gentry:
      download: https://members.onepeloton.com/classes/player/1c97dccf5afe470280a6f29dcdee3f80
      overrides:
        tv_show_directory: /media/peloton/Rowing/Becs Gentry
        season_number: 20
        episode_number: 77
  = Row Bootcamp (30 min):
    '30 min Bootcamp: 50-50 with Katie Wang':
      download: https://members.onepeloton.com/classes/player/aaab465eece040749f32cfba5187f0de
      overrides:
        tv_show_directory: /media/peloton/Row Bootcamp/Katie Wang
        season_number: 30
        episode_number: 109
