__preset__:
  overrides:
    tv_show_directory: /media/peloton
    only_recent_date_range: 24months
    only_recent_max_files: 300
  output_options:
    output_directory: '{tv_show_directory}'
    file_name: S{season_number}E{episode_number} - {upload_date} - {title}/S{season_number}E{episode_number} - {upload_date} - {title}.{ext}
    thumbnail_name: S{season_number}E{episode_number} - {upload_date} - {title}/S{season_number}E{episode_number} - {upload_date} - {title}-thumb.jpg
    info_json_name: S{season_number}E{episode_number} - {upload_date} - {title}/S{season_number}E{episode_number} - {upload_date} - {title}.info.json
  throttle_protection:
    sleep_per_download_s:
      min: 120
      max: 270
    sleep_per_subscription_s:
      min: 60
      max: 90
    max_downloads_per_subscription:
      min: 25
      max: 75
    subscription_download_probability: 1
  ytdl_options:
    usenetrc: true
    format: bestvideo+bestaudio/bestaudio
    merge_output_format: mp4
Plex TV Show by Date:
  = Walking (20 min):
    20 min Pop Walk with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/fe30657f7b164c37ae56f0e0aa3324a9
      overrides:
        tv_show_directory: /media/peloton/Walking/Hannah Frankson
        season_number: 20
        episode_number: 38
    20 min Walk + Run with Jon Hosking:
      download: https://members.onepeloton.com/classes/player/1268de875aa34bf1ba9a40262c5c24de
      overrides:
        tv_show_directory: /media/peloton/Walking/Jon Hosking
        season_number: 20
        episode_number: 57
  = Strength (30 min):
    30 min 2000s Full Body Strength with Logan Aldridge:
      download: https://members.onepeloton.com/classes/player/e55a5040e7dc4bdaabf6fd2fcc71acdc
      overrides:
        tv_show_directory: /media/peloton/Strength/Logan Aldridge
        season_number: 30
        episode_number: 48
  = Strength (10 min):
    10 min Core Strength with Ben Alldis:
      download: https://members.onepeloton.com/classes/player/6162081163e34ea8934fdc6da9891bcc
      overrides:
        tv_show_directory: /media/peloton/Strength/Ben Alldis
        season_number: 10
        episode_number: 61
    10 min Chest & Back Strength with Ben Alldis:
      download: https://members.onepeloton.com/classes/player/218d8311fa0d43c8a11172bd1355aadf
      overrides:
        tv_show_directory: /media/peloton/Strength/Ben Alldis
        season_number: 10
        episode_number: 62
    10 min Core Strength with Adrian Williams:
      download: https://members.onepeloton.com/classes/player/52acb0cece044a7392998d3ab1616152
      overrides:
        tv_show_directory: /media/peloton/Strength/Adrian Williams
        season_number: 10
        episode_number: 63
  = Strength (60 min):
    60 min Total Strength with Andy Speer:
      download: https://members.onepeloton.com/classes/player/ee859d6588c84c9896aa3cbe0888cb1c
      overrides:
        tv_show_directory: /media/peloton/Strength/Andy Speer
        season_number: 60
        episode_number: 8
  = Strength (20 min):
    20 min Glutes & Legs Strength with Adrian Williams:
      download: https://members.onepeloton.com/classes/player/6873c46c4e304806b61c04234b0794d6
      overrides:
        tv_show_directory: /media/peloton/Strength/Adrian Williams
        season_number: 20
        episode_number: 85
  = Yoga (30 min):
    30 min Yoga Flow with Aditi Shah:
      download: https://members.onepeloton.com/classes/player/f6326bb79aa343faacb71791d222e70f
      overrides:
        tv_show_directory: /media/peloton/Yoga/Aditi Shah
        season_number: 30
        episode_number: 112
    '30 min Vibe & Flow: Reggaeton with Chelsea Jackson Roberts':
      download: https://members.onepeloton.com/classes/player/11de5fc8b54144e1a5ab8a3f2d453e69
      overrides:
        tv_show_directory: /media/peloton/Yoga/Chelsea Jackson Roberts
        season_number: 30
        episode_number: 113
    30 min Pop Yoga Flow with Anna Greenberg:
      download: https://members.onepeloton.com/classes/player/3483c7c97b9e4cd39ab88e9b3d6d5bd4
      overrides:
        tv_show_directory: /media/peloton/Yoga/Anna Greenberg
        season_number: 30
        episode_number: 114
    30 min Yoga Flow with Kirra Michel:
      download: https://members.onepeloton.com/classes/player/496b679b37b747a09b3302a86e39a8ae
      overrides:
        tv_show_directory: /media/peloton/Yoga/Kirra Michel
        season_number: 30
        episode_number: 115
    30 min Power Flow with Anna Greenberg:
      download: https://members.onepeloton.com/classes/player/9646fd9a86094fc3983d695d3e69d288
      overrides:
        tv_show_directory: /media/peloton/Yoga/Anna Greenberg
        season_number: 30
        episode_number: 116
  = Yoga (45 min):
    45 min Slow Flow with Anna Greenberg:
      download: https://members.onepeloton.com/classes/player/a669ecce9802490a9ac67ac2f85b9ccc
      overrides:
        tv_show_directory: /media/peloton/Yoga/Anna Greenberg
        season_number: 45
        episode_number: 13
  = Meditation (10 min):
    10 min Daily Meditation with Kirra Michel:
      download: https://members.onepeloton.com/classes/player/9cba194427f943cb8a524c5ce29520e4
      overrides:
        tv_show_directory: /media/peloton/Meditation/Kirra Michel
        season_number: 10
        episode_number: 208
  = Stretching (10 min):
    10 min Full Body Stretch with Adrian Williams:
      download: https://members.onepeloton.com/classes/player/0102bca682594fedb4cbd93bc3dc9de2
      overrides:
        tv_show_directory: /media/peloton/Stretching/Adrian Williams
        season_number: 10
        episode_number: 76
  = Cycling (45 min):
    45 min Power Zone Endurance Ride with Ben Alldis:
      download: https://members.onepeloton.com/classes/player/f9671bfa402540e19140c9d832838744
      overrides:
        tv_show_directory: /media/peloton/Cycling/Ben Alldis
        season_number: 45
        episode_number: 47
  = Cycling (30 min):
    30 min Hip Hop Ride with Alex Toussaint:
      download: https://members.onepeloton.com/classes/player/9cdced6341e944bc95092d027639867c
      overrides:
        tv_show_directory: /media/peloton/Cycling/Alex Toussaint
        season_number: 30
        episode_number: 149
    30 min Hip Hop Ride with Camila Ramón:
      download: https://members.onepeloton.com/classes/player/f5ebda5a5b6d4d5faf10a1ef1b8ddcd7
      overrides:
        tv_show_directory: /media/peloton/Cycling/Camila Ramón
        season_number: 30
        episode_number: 150
    30 min Pop Ride with Jenn Sherman:
      download: https://members.onepeloton.com/classes/player/333d40d6a1e34961af6343d8a2ba9a63
      overrides:
        tv_show_directory: /media/peloton/Cycling/Jenn Sherman
        season_number: 30
        episode_number: 151
    30 min Feel Good Ride with Ally Love:
      download: https://members.onepeloton.com/classes/player/9dcd3e8a595f4c1892bd3f96e63d0d6e
      overrides:
        tv_show_directory: /media/peloton/Cycling/Ally Love
        season_number: 30
        episode_number: 152
    30 min Classic Rock Ride with Ben Alldis:
      download: https://members.onepeloton.com/classes/player/1c7e1fbb07594259a00d9e7323113107
      overrides:
        tv_show_directory: /media/peloton/Cycling/Ben Alldis
        season_number: 30
        episode_number: 153
    30 min 90s Rock Ride with Emma Lovewell:
      download: https://members.onepeloton.com/classes/player/d94896fde49d431c9a82fd7788441b40
      overrides:
        tv_show_directory: /media/peloton/Cycling/Emma Lovewell
        season_number: 30
        episode_number: 154
    30 min Low Impact Ride with Leanne Hainsby-Alldis:
      download: https://members.onepeloton.com/classes/player/458de7b8e1ba4de0aa2c1ffe7a164748
      overrides:
        tv_show_directory: /media/peloton/Cycling/Leanne Hainsby-Alldis
        season_number: 30
        episode_number: 155
    30 min EDM Ride with Olivia Amato:
      download: https://members.onepeloton.com/classes/player/55cd22773fee472ebfff265c90322cf4
      overrides:
        tv_show_directory: /media/peloton/Cycling/Olivia Amato
        season_number: 30
        episode_number: 156
    30 min Metal Ride with Charlotte Weidenbach:
      download: https://members.onepeloton.com/classes/player/dbbab4f38a034cda8bb4a068601136ba
      overrides:
        tv_show_directory: /media/peloton/Cycling/Charlotte Weidenbach
        season_number: 30
        episode_number: 157
  = Cycling (10 min):
    'Extra 10: Tabata Ride with Olivia Amato':
      download: https://members.onepeloton.com/classes/player/5fb5bd16a4d1497ca5e19564255dad58
      overrides:
        tv_show_directory: /media/peloton/Cycling/Olivia Amato
        season_number: 10
        episode_number: 10
  = Cycling (20 min):
    20 min Beginner Ride with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/3999509920d647869916871a7787dd28
      overrides:
        tv_show_directory: /media/peloton/Cycling/Hannah Frankson
        season_number: 20
        episode_number: 74
    20 min HIIT Ride with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/856dd27b0a0f4007a37442b826de341d
      overrides:
        tv_show_directory: /media/peloton/Cycling/Hannah Frankson
        season_number: 20
        episode_number: 75
  = Cycling (15 min):
    15 min Low Impact Ride with Camila Ramón:
      download: https://members.onepeloton.com/classes/player/785338e49e94404c8a5554e0a577dc72
      overrides:
        tv_show_directory: /media/peloton/Cycling/Camila Ramón
        season_number: 15
        episode_number: 23
    15 min Hip Hop Ride with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/bf635326a75943f7bc1191decddc7bab
      overrides:
        tv_show_directory: /media/peloton/Cycling/Hannah Frankson
        season_number: 15
        episode_number: 24
  = Cycling (60 min):
    60 min 80s Ride with Jenn Sherman:
      download: https://members.onepeloton.com/classes/player/0d0ee197a69c4cac8c2e9e9b49857c68
      overrides:
        tv_show_directory: /media/peloton/Cycling/Jenn Sherman
        season_number: 60
        episode_number: 5
  = Cycling (90 min):
    90 min Power Zone Endurance Ride with Denis & Matt:
      download: https://members.onepeloton.com/classes/player/aab6d338d6e04d6780873bdabafc1d45
      overrides:
        tv_show_directory: /media/peloton/Cycling/Denis & Matt
        season_number: 90
        episode_number: 1
  = Running (10 min):
    'Extra 10: Endurance with Hannah Frankson':
      download: https://members.onepeloton.com/classes/player/6aa9343e1ab04656abacda288058db55
      overrides:
        tv_show_directory: /media/peloton/Running/Hannah Frankson
        season_number: 10
        episode_number: 9
  = Running (45 min):
    45 min Endurance Run with Marcel Dinkins:
      download: https://members.onepeloton.com/classes/player/9651ebc6c28f4c738bcacc63a563f9b3
      overrides:
        tv_show_directory: /media/peloton/Running/Marcel Dinkins
        season_number: 45
        episode_number: 19
  = Running (30 min):
    30 min Trap Run with Kirsten Ferguson:
      download: https://members.onepeloton.com/classes/player/0d17035dd4d34692b83468e5a0d7a5df
      overrides:
        tv_show_directory: /media/peloton/Running/Kirsten Ferguson
        season_number: 30
        episode_number: 114
    30 min 80s Run with Joslyn Thompson Rule:
      download: https://members.onepeloton.com/classes/player/99fc4b66d2054e24bf5d9b3ced120d67
      overrides:
        tv_show_directory: /media/peloton/Running/Joslyn Thompson Rule
        season_number: 30
        episode_number: 115
    30 min Rising Pop Run with Robin Arzón:
      download: https://members.onepeloton.com/classes/player/d903481572a04b80b0b080f28194c22b
      overrides:
        tv_show_directory: /media/peloton/Running/Robin Arzón
        season_number: 30
        episode_number: 116
    30 min Intervals Run with Alex Karwoski:
      download: https://members.onepeloton.com/classes/player/f7177d1303694ecf9d6dee01255b0e07
      overrides:
        tv_show_directory: /media/peloton/Running/Alex Karwoski
        season_number: 30
        episode_number: 117
    30 min 2010s Run with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/1c609958a1364751ae2862d9d565f623
      overrides:
        tv_show_directory: /media/peloton/Running/Hannah Frankson
        season_number: 30
        episode_number: 118
    30 min House Run with Olivia Amato:
      download: https://members.onepeloton.com/classes/player/ee1b2691abb346efb1b5e053bc39ca0e
      overrides:
        tv_show_directory: /media/peloton/Running/Olivia Amato
        season_number: 30
        episode_number: 119
    30 min Endurance Run with Hannah Frankson:
      download: https://members.onepeloton.com/classes/player/9c0234aa44264df8b6585e495f671de1
      overrides:
        tv_show_directory: /media/peloton/Running/Hannah Frankson
        season_number: 30
        episode_number: 120
  = Running (20 min):
    20 min 2000s Run with Jon Hosking:
      download: https://members.onepeloton.com/classes/player/625421dd04ec42d09527f61d28d387c7
      overrides:
        tv_show_directory: /media/peloton/Running/Jon Hosking
        season_number: 20
        episode_number: 68
  = Walking (30 min):
    30 min Hike with Kirsten Ferguson:
      download: https://members.onepeloton.com/classes/player/79c4c8d15564473892fa801f51b76e66
      overrides:
        tv_show_directory: /media/peloton/Walking/Kirsten Ferguson
        season_number: 30
        episode_number: 97
    30 min Hike with Joslyn Thompson Rule:
      download: https://members.onepeloton.com/classes/player/cda681c716c34a02a92202f5d138fdfa
      overrides:
        tv_show_directory: /media/peloton/Walking/Joslyn Thompson Rule
        season_number: 30
        episode_number: 98
    30 min Pride Pop Walk with Matty Maggiacomo:
      download: https://members.onepeloton.com/classes/player/7a22ba645d4d4962886ecd906dc0356e
      overrides:
        tv_show_directory: /media/peloton/Walking/Matty Maggiacomo
        season_number: 30
        episode_number: 99
  = Walking (10 min):
    'Extra 10: Hike with Jon Hosking':
      download: https://members.onepeloton.com/classes/player/5e40aaf249514b079141b7cba5aea516
      overrides:
        tv_show_directory: /media/peloton/Walking/Jon Hosking
        season_number: 10
        episode_number: 15
  = Walking (45 min):
    45 min On the Dancefloor Walk with Jess King:
      download: https://members.onepeloton.com/classes/player/e03693ed5030430a99a521d8a0dd9d9c
      overrides:
        tv_show_directory: /media/peloton/Walking/Jess King
        season_number: 45
        episode_number: 17
  = Tread Bootcamp (60 min):
    Sims 60 with Jess Sims:
      download: https://members.onepeloton.com/classes/player/b9b0519fc671474d889d2b8382f6b490
      overrides:
        tv_show_directory: /media/peloton/Tread Bootcamp/Jess Sims
        season_number: 60
        episode_number: 31
  = Tread Bootcamp (45 min):
    Thunder 45 with Adrian Williams:
      download: https://members.onepeloton.com/classes/player/e5367c3471724c5da4e6561be5dd090f
      overrides:
        tv_show_directory: /media/peloton/Tread Bootcamp/Adrian Williams
        season_number: 45
        episode_number: 100
  = Rowing (30 min):
    30 min Rock Row with Katie Wang:
      download: https://members.onepeloton.com/classes/player/11e2648136f54588a1c5f0292ae13ec4
      overrides:
        tv_show_directory: /media/peloton/Rowing/Katie Wang
        season_number: 30
        episode_number: 45
    30 min Endurance Row with Alex Karwoski:
      download: https://members.onepeloton.com/classes/player/5787c57296f3452a8951aa0a72a7e76b
      overrides:
        tv_show_directory: /media/peloton/Rowing/Alex Karwoski
        season_number: 30
        episode_number: 46
