apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich
  annotations:
    external-dns.alpha.kubernetes.io/target: haynesnetwork.com
    kubernetes.io/ingress.class: traefik-external
    # Homepage
    gethomepage.dev/href: "https://immich.haynesnetwork.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Photo management platform
    gethomepage.dev/group: Media
    gethomepage.dev/name: Immich
    gethomepage.dev/app: immich-server
    gethomepage.dev/icon: sh-immich.svg
    gethomepage.dev/siteMonitor: "https://immich.haynesnetwork.com"
    gethomepage.dev/widget.type: "immich"
    gethomepage.dev/widget.url: "https://immich.haynesnetwork.com"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_IMMICH_API_KEY}}"
    gethomepage.dev/widget.version: "2"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`immich.haynesnetwork.com`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: immich-server
          port: 2283
  tls:
    secretName: certificate-haynesnetwork