---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app snapshot-controller
  namespace: flux-system
spec:
  targetNamespace: volsync-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 15m
  retryInterval: 1m
  timeout: 2m
  prune: false
  wait: true
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  path: ./kubernetes/main/apps/storage/volsync-system/snapshot-controller/app
  postBuild:
    substitute:
      APP: *app

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app snapshot-controller
  namespace: volsync-system
spec:
  targetNamespace: volsync-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 15m
  retryInterval: 1m
  timeout: 2m
  prune: true
  wait: true
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  path: ./kubernetes/main/apps/storage/volsync-system/snapshot-controller/app
  postBuild:
    substitute:
      APP: *app
