---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app openebs
  namespace: flux-system
spec:
  targetNamespace: &namespace openebs-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/apps/storage/openebs-system/openebs/app
  # Migration safety: keep the old KS from pruning its inventory when we move
  # the active Kustomization into the openebs-system namespace.
  prune: false
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  suspend: true
  wait: true
  interval: 30m
  timeout: 5m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
---
# Flux Kustomization (in target namespace).
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
  namespace: openebs-system
spec:
  targetNamespace: openebs-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: openebs
  path: ./kubernetes/main/apps/storage/openebs-system/openebs/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  wait: true
  interval: 30m
  timeout: 5m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: openebs
      namespace: openebs-system
