# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg
  namespace: flux-system
spec:
  suspend: true
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
  path: ./kubernetes/main/apps/database/cloudnative-pg/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  wait: true
  interval: 15m
  retryInterval: 1m  
  timeout: 2m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg
  namespace: database
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
  path: ./kubernetes/main/apps/database/cloudnative-pg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  wait: true
  interval: 15m
  retryInterval: 1m  
  timeout: 2m

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg-cluster
  namespace: flux-system
spec:
  suspend: true
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg
  path: ./kubernetes/main/apps/database/cloudnative-pg/cluster
  prune: false
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  wait: true
  interval: 15m
  retryInterval: 1m  
  timeout: 2m

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg-cluster
  namespace: database
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  path: ./kubernetes/main/apps/database/cloudnative-pg/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  wait: true
  interval: 15m
  retryInterval: 1m  
  timeout: 2m
