---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvdp
  namespace: kube-system
spec:
  interval: 30m
  timeout: 3m
  url: https://nvidia.github.io/k8s-device-plugin
