---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./bjw-s-labs.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./piraeus.yaml
  - ./rook-ceph.yaml
  - ./backube.yaml
  - ./metallb.yaml
  - ./kubernetes-sigs-descheduler.yaml
  - ./whereabouts.yaml
