---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appdaemon
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: appdaemon-secret
    template:
      engineVersion: v2
      data:
        TOKEN: "{{ .TOKEN }}"
        SSH_PUBLIC_KEY: "{{ .SSH_PUBLIC_KEY }}"
        secrets.yaml: |
          token: "{{ .TOKEN }}"
        appdaemon.yaml: |
          appdaemon:
            time_zone: America/New_York
            latitude: 0
            longitude: 0
            elevation: 0
          plugins:
            HASS:
              type: hass
              ha_url: http://home-assistant.home-automation.svc.cluster.local:8123
              token: !secret token
              ws_max_msg_size: 8388608
          http:
            url: http://0.0.0.0:5050
          api:
          admin:
  dataFrom:
    - extract:
        key: appdaemon
