---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../../shared/components/common/repos/app-template
  - ../../../../../shared/components/gatus/gaurded
  - ../../../../../shared/components/volsync/aws
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./multus-iot.yaml
configMapGenerator:
  - name: zigbee2mqtt-loki-rules
    files:
      - zigbee2mqtt.yaml=./resources/lokirule.yaml
    options:
      labels:
        loki_rule: "true"
generatorOptions:
  disableNameSuffixHash: true
