---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: prometheus
        group: internal
        url: "10.43.0.10"
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: "prometheus.haynesops.com"
          query-type: A
        conditions:
          - "[DNS_RCODE] == NOERROR"
        alerts:
          - type: pushover
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: alertmanager
        group: internal
        # Alertmanager is behind auth; consider any non-5xx as "up"
        url: "https://alertmanager.haynesops.com/"
        interval: 1m
        conditions:
          - "[STATUS] < 500"
        alerts:
          - type: pushover
