---
# Flux Kustomization (in target namespace).
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates
  namespace: cert-manager
spec:
  targetNamespace: cert-manager
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: cert-manager-issuers
      namespace: cert-manager
    - name: external-secrets-stores
      namespace: flux-system
  path: ./kubernetes/main/apps/cert-manager/certificates/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  wait: false
  interval: 15m
  retryInterval: 1m
  timeout: 2m
