apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
spec:
  chart:
    spec:
      chart: reflector
      version: 7.1.x
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: kube-system
  interval: 15m
  timeout: 5m
  releaseName: reflector
  values: values.yaml # Take all defaults