---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./pvc.yaml
  - ./ingressroute.yaml
  - ./externalsecret.yaml
  - ../../../../../shared/templates/gatus/gaurded
configMapGenerator:
  - name: comfyui-configmap
    files:
      - config.ini=./resources/config.ini
generatorOptions:
  disableNameSuffixHash: true
