---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-dashboard-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: rook
        group: internal
        url: "10.43.0.10"
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: "rook.haynesops.com"
          query-type: A
        conditions:
          - "[DNS_RCODE] == NOERROR"
        alerts:
          - type: pushover
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rgw-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: rgw
        group: internal
        url: "10.43.0.10"
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: "rgw.haynesops.com"
          query-type: A
        conditions:
          - "[DNS_RCODE] == NOERROR"
        alerts:
          - type: pushover
