---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ha-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ha-mcp-secret
    template:
      engineVersion: v2
      data:
        HOMEASSISTANT_TOKEN: "{{ .HOMEASSISTANT_TOKEN }}"
        MCP_SECRET_PATH: "{{ .MCP_SECRET_PATH }}"
  dataFrom:
    - extract:
        key: ha-mcp
