---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage-util
components:
  - ../../../../shared/components/common/repos/app-template
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./rsync-music/ks.yaml
  - ./rsync-photos/ks.yaml
  - ./rsync-scans/ks.yaml
