# Only overrides specific settings, lets envs handle secrets
hass_img_path: "/immich-album"
update_interval_minutes: 15
num_photos: 10
log_level: "DEBUG"

# Photo filters - list of filter sets to cycle through
filters:
  - name: "Fireworks"
    selector_type: "smart-rng"
    search_query: "Fireworks"
    max_search_results: 500

  - name: "Random Christmas Card"
    selector_type: "random"
    taken_after: "2025-10-20"
    taken_before: "2025-10-21"

  - name: "Tom"
    selector_type: "random"
    people: ["Tom Haynes"]
    taken_after: "2023-01-01"

  - name: "Winter Baby"
    selector_type: "smart-rng"
    search_query: "Winter Baby"
    max_search_results: 500
