# Only overrides specific settings, lets envs handle secrets
hass_img_path: "/immich-album"
update_interval_minutes: 15
num_photos: 10
log_level: "DEBUG"

# Photo filters - list of filter sets to cycle through
filters:
  - name: "Random Christmas Card"
    selector_type: "random"
    taken_after: "2025-10-20"
    taken_before: "2025-10-21"

  - name: "Christmas Baby"
    selector_type: "smart-rng"
    search_query: "Christmas Baby"
    max_search_results: 500

  - name: "Random Christmas 2023"
    selector_type: "random"
    taken_after: "2023-12-24"
    taken_before: "2023-12-26"

  - name: "Christmas Photoshoot"
    selector_type: "smart-rng"
    search_query: "Christmas Photoshoot"
    max_search_results: 500
