# Only overrides specific settings, lets envs handle secrets
hass_img_path: "/immich-album"
update_interval_minutes: 15
num_photos: 10
log_level: "DEBUG"

# Photo filters - list of filter sets to cycle through
filters:
  - name: "Random Christmas 2024"
    selector_type: "random"
    taken_after: "2024-12-25"
    taken_before: "2024-12-26"

  - name: "Random Christmas Card"
    selector_type: "random"
    taken_after: "2025-10-10"
    taken_before: "2025-10-21"

  - name: "Random Christmas 2023"
    selector_type: "random"
    taken_after: "2023-12-24"
    taken_before: "2025-12-26"

  - name: "Christmas Presents"
    selector_type: "smart-rng"
    search_query: "Christmas Presents"
    max_search_results: 100
