# Only overrides specific settings, lets envs handle secrets
hass_img_path: "/immich-album"
update_interval_minutes: 15
num_photos: 10
log_level: "DEBUG"

# Photo filters - list of filter sets to cycle through
filters:
  - name: "Winter Wonderland"
    selector_type: "smart-rng"
    search_query: "Winter Wonderland"
    max_search_results: 100

  - name: "Christmas Tree"
    selector_type: "smart-rng"
    search_query: "Christmas Tree"
    max_search_results: 100

  - name: "Family Gatherings for Thanksgiving"
    selector_type: "smart-rng"
    search_query: "Family Gatherings for Thanksgiving"
    max_search_results: 100

  - name: "Christmas Presents"
    selector_type: "smart-rng"
    search_query: "Christmas Presents"
    max_search_results: 100