# Only overrides specific settings, lets envs handle secrets
hass_img_path: "/immich-album"
update_interval_minutes: 15
num_photos: 10
log_level: "DEBUG"

# Photo filters - list of filter sets to cycle through
filters:
  - name: "Penelope's Birthday"
    selector_type: "smart-rng"
    search_query: "Penelope's Birthday"
    max_search_results: 500

  - name: "Baby Photo Shoot"
    selector_type: "smart-rng"
    search_query: "Baby Photo Shoot"
    max_search_results: 500

  - name: "Penelope"
    selector_type: "random"
    people: ["Penelope Haynes"]

  - name: "Tom"
    selector_type: "random"
    people: ["Tom Haynes"]
    taken_after: "2023-01-01"
