---
# Flux Kustomization (in target namespace).
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  targetNamespace: external-secrets
  commonMetadata:
    labels:
      app.kubernetes.io/name: external-secrets
  interval: 15m
  retryInterval: 1m
  timeout: 2m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  path: ./kubernetes/main/apps/external-secrets/external-secrets/app
---
# Flux Kustomization (in target namespace).
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-stores
  namespace: external-secrets
spec:
  targetNamespace: external-secrets
  commonMetadata:
    labels:
      app.kubernetes.io/name: external-secrets-stores
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
    - name: onepassword-connect
      namespace: flux-system
  interval: 15m
  retryInterval: 1m
  timeout: 2m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: haynes-ops
    namespace: flux-system
  path: ./kubernetes/main/apps/external-secrets/external-secrets/stores
